- src/image-png.c
Fix the incorrect rendering of PNG files and pass the test of PNG color formats include RGB, RGBA, PALETTE and GRAY.
> Fix incorrect background pixmap rendering

- src/draw.c
The function twin_pixmap_read_xform_8() applies a linear transformation to an 8-bit pixmap. Due to discretization considerations in computer graphics, the output is usually calculated using backward interpolation (i.e.,_pix_saucemix).
This commit identifies two potential bugs in the implementation. The first bug is that the coordinate calculation for pts[3] should be (sx + 1, sy + 1). The second bug is that _pix_saucemix() should take pts[3] instead of pts[4]. Using pts[4] not only violates the definition of `twin_a8_t pts[4];` but also makes no sense since the four calls to _get_pix_8() are intended to obtain the top-left, top-right, bottom-left, and bottom-right pixels.
Additionally, this commit eliminates the only existing warnings in the project.
> Fix implementation of 8-bit pixmap transformation

- .ci/check-format.sh
- .ci/check-newline.sh
- .github/workflows/main.yml
Indent all C source files with clang-format-12 and force newline at the end of files.
At present, "make" is the only way to validate the build. Later, we may perform headless validation for a file loopback device-based backend, allowing checks of the window system internals.
> Add preliminary CI scripts

- src/fixed.c
The original fixed point sqrt can not calculate sqrt of numbers less than 1. Implement a new sqrt calculation that is more precise and without fixed point multiplication.
Below is the comparison of sqrt from 0~2. "math.h" stands for function 'sqrt()' from library math.h. "original" stands for original sqrt implementation. "precise" stands for new implemented method.
> Enhance the precision of fixed-point square root computations

- tools/font-edit/twin-fedit.c
In C99 7.19.6.5 sprintf, "If copying takes place between objects that overlap, the behavior is undefined".
Replace sprintf with snprintf and provide a clear buffer size to ensure undefined behavior does not occur.
And the sizeof(buff) + 1 includes the null terminator.
> Replace sprintf with snprintf

- backend/sdl.c
Function _twin_sdl_destroy destroys the screen before the backend destroyed. This causes a segmentation fault or an endless loop. This commit changes the sequence of destruction in the function.
> Fix segmentation fault after destorying window

- include/twin_private.h
Describing the type using only the 12.4, 24.8, or 2.6 format is unclear for reading and doesn't clearly indicate
how many bits are used for the integer and fractional parts.
Add a brief explanation to clarify the meaning of the numbers before and after the decimal point.
The number before the decimal point represents how many bits are used for the integer part, and the number after the decimal point represents how many bits are used for the fractional part.
> Describe fixed-point types

- src/spline.c
The starting point and the first left segment's A point are the same. The ending point and the original spline's D point are the same.
> Remove the duplicate starting and ending points

- tools/font-edit/twin-fedit.c
- tools/font-edit/twin-fedit.h
Currently, the font-edit tool relies on Xlib. According to #7, font-edit should be restructured using SDL2 to enhance portability.
Before proceeding with this work, it is necessary to understand the significance and operational principles of TWIN’s existing functionality. Therefore, we first need to add clear comments to the typedefs and functions in twin-fedit.h to provide a basis for future modifications and porting to SDL2.
To avoid disrupting other developers who might be using the tool during this process, a new branch named font-edit is created.
> font-edit: Improve the type descriptions

- .gitignore
Add exclusions for swap files, Vim session records, and tag files using the .gitignore generator
Re-open for #23:
> Use tools such as [.gitignore generator](https://mrkandreev.name/snippets/gitignore-generator/) to improve .gitignore. In particular, C and Python are major programming languages used by this project.
> Exclude more generated files from the Git repository

- apps/calc.c
According to #25, we find that the input number is random if the digits of the number is larger than 9 digits.
The type of calc->stack[0] is int, and the maximum value for an int is 2,147,483,647. Conservatively, we ensure that when the length reaches 9 digits, pressing the digit button will not increase the number of digits.
> calc: Set maximum digit length to 9

- src/image.c
Based on the [PNG header format](http://www.libpng.org/pub/png/spec/1.2/PNG-Structure.html) and [JPG/JPEG header format](https://www.file-recovery.com/jpg-signature-format.htm)。Parsing the header of image to determine if the supported format is PNG or JPEG.
> Determine supported image file types by checking the file header

- apps/spline.c
The spline demo program previously initialized the cap style as 'butt', which caused inconsistent spline rendering with an unexpected blank half-circle. This commit changes the cap style to 'round', ensuring more consistent spline movement and rendering without flickering.
> spline: Initialize cap style to round

- src/geom.c
- tools/font-edit/sfit.c
In the comment, "AX+BY+C" was typed as "AX+BC+C".
> Fix the typo

- include/twin_private.h
Add the helper macro for type conversion from `twin_dfixed_t` to `twin_sfixed_t`. Add the helper macro for multiplication and division, where both operands and the result are of type `twin_dfixed_t` or `twin_sfixed_t`.
> Consolidate macros for fixed-point multiplication and division

- Makefile
- backend/sdl.c
- configs/Kconfig
- include/twin_private.h
- src/image-gif.c
- src/image-jpeg.c
- src/image.c
- src/log.c
- src/log.h
Currently, various messages are displayed while the window system is running, but their format and usage are inconsistent. Additionally, depending on the scenario, it may be useful to adjust the color scheme or disable logging output altogether.
The [rxi/log.c](https://github.com/rxi/log.c) offers a robust solution for these needs, and it would be beneficial to integrate it into the core implementation of the window system to standardize logging and enhance flexibility.
- `log_trace`
- `log_debug`
- `log_info`
- `log_warn`
- `log_error`
- `log_fatal`
Close #47
> Consolidate logging with a unified interface

- src/image.c
The PNG file format maintains consistent byte order across different systems, despite variations in the underlying system's native endianness.
> Ensure consistent byte order in PNG file

- src/pixmap.c
Resolved a heap-buffer-overflow in _twin_edge_fill by adding proper bounds checking to prevent _span_fill from accessing out-of-bounds memory. The MIN macro was introduced to ensure x coordinates do not exceed the width of the pixmap.
We fix the part of the memory issues detected by AddressSanitizer:
See: #49
The current Sanitizer result is:
```
=================================================================
==11185==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 49152 byte(s) in 1 object(s) allocated from:
#0 0x7ff3cd4ebb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x55bc52a396a6 in _twin_gif_to_pixmap (/home/ben/side_project/mado/demo-sdl+0x396a6)
Direct leak of 2064 byte(s) in 2 object(s) allocated from:
#0 0x7ff3cd4ebf30 in realloc …
```
> Fix heap-buffer-overflow in _twin_edge_fill function

- src/timeout.c
I noticed the GIF frame rate is slower than expected when combined with the clock app. Upon checking the `_twin_run_timeout` function, I discovered that the processing queue handles events from larger to smaller time ticks. I fixed this by changing the order to process from smaller to larger time ticks, ensuring timeout events are handled sequentially.
Before:
After:
> Fix timeout processing order

- apps/multi.c
- backend/sdl.c
- src/image-gif.c
To fix the heap-use-after-free issue when `screen` is accessed by the `twin_sdl_work()` function, remove the `_twin_sdl_destroy(screen, tx)` operation. Additionally, to address the memory leak, add the `twin_path_destroy(path)` function to ensure the unused path is properly destroyed.
Close sysprog21#49
> Fix the heap-use-after-free and memory leak

- mk/common.mk
- mk/toolchain.mk
In preparation for cross-compilation support, the toolchain specific configurations have been decoupled from the build system. Preliminary checks have been added to determine the supported compilers, GCC and Clang. When 'CROSS_COMPILE' is set, the build system will honor it and set CC accordingly. Currently, only the GNU toolchain is supported for cross-compilation.
> Decouple toolchain configurations

- apps/calc.c
- apps/clock.c
- apps/hello.c
- apps/multi.c
- include/twin.h
- src/draw.c
- src/font.c
- src/path.c
- src/window.c
There are four supported font styles, originally defined using macros. Switching to enum for these identifiers improves code clarity, self- documentation, and ensures type safety when working with related constants.
> Use enum for font styles instead of macros

- Makefile
- README.md
- backend/fbdev.c
- backend/linux_input.c
- backend/linux_input.h
- configs/Kconfig
This pull request introduces Linux framebuffer backend and mouse event handling for `Mado`.
To test the program, simply type:
```shell
$ sudo ./demo-fbdev
```
`Mado` will automatically switch the virtual terminal. (For most case, it should be VT3)
The user should see the following result on the screen:
After finished testing, the user can switch back to the desktop with `Ctrl+Alt+F1`.
> Support Linux framebuffer and input system

- src/spline.c
The evaluation testbed is [font-edit](https://github.com/sysprog21/mado/tree/main/tools/font-edit), where I modified the implementation to use fixed-point arithmetic.
The font generated by the [original implementation](https://github.com/sysprog21/mado/commit/6d85b4280db3288485c9261b512ec1640697a678) is as follows:
The font generated by the implementation of decomposing splines with flexibly updated t is as follows:
> Decompose splines with t flexibly updated

- Makefile
- README.md
- configs/Kconfig
- src/pixman.c
- src/pixmap.c
According to issue #6, I replace original image compositing and trapezoid rasterization with Pixman function. Briefly, include:
- pixman_image_composite: image compositing
- pixman_fill_rect: use pixman_image_fill_rectangles to fill the image with retangles
- pixman_image_fill_boxes: span is filled with the boxs
Close #6
We compare the results of the original method with those rewritten using the Pixman library:
(Left image: original method, and right image: Pixman method)
- Hello world:
- Calculator(Original):
- Viewer(Original):
- Multi-demo(Original):
> Utilize pixman for efficient pixel manipulation

- Makefile
- README.md
- backend/linux_input.c
`udev` (`userspace /dev`) is a device manager for the Linux kernel. By monitoring `add` and `remove` events from `udev`, we can dynamically update the event device file descriptors table to enable device hot-plugging and removal.
To test the modified code, compile `mado` with the `Linux framebuffer` backend.
1. Switch to a new virtual terminal (VT) by pressing `Ctrl+Alt+Fn` (e.g., `Ctrl+Alt+F3`) and then execute:
```shell
$ sudo ./demo-fbdev
```
2. Test the new feature by unplugging and reconnecting the mouse.
3. Return to the desktop environment with `Ctrl+Alt+F1`.
> Support input device hot-plugging and removal via udev

- backend/fbdev.c
- backend/linux_vt.h
Move Linux VT into separate files to enable developers to use it in other backhands, such as Linux DRM.
> Decouple Linux VT

- backend/fbdev.c
Issue https://github.com/sysprog21/mado/issues/62 
The width of screen may be different from the virtual resolution.
In `apps/main.c`, the default value of `WIDTH` and `HEIGHT` are 640 and 480, but the visual resolution are set to 1920 and 1080 on my machine.
The different width will draw three screens on the display as the below screenshot.
Before:
After:
The reason to use ~`xres_virtual`~  `line_length` as the width and not to use `xres` in [`struct fb_var_screeninfo`](https://github.com/torvalds/linux/blob/e42b1a9a2557aa94fee47f078633677198386a52/include/linux/fb.h#L828):
On VirtualBox, the visible resolution of virtual terminal, which switched by `ctrl+alt+f3`, is set to 800x600, but the virtual solution is set to 2048x2048. On my physical machine, Asus latop and Ubuntu system, these …
> Fix memory region in framebuffer

- backend/fbdev.c
Mado currently uses 32-bit bpp, supporting display devices on desktop/laptop computers, while Raspberry Pi devices use 16-bit bpp. To improve mado’s compatibility across various Linux framebuffer environments, testing showed that
tx->fb_var.bits_per_pixel automatically sets the appropriate bpp without requiring manual configuration.
> Support 16/24/32 bit color depth

- apps/multi.c
- apps/spline.c
- include/twin.h
- include/twin_private.h
- src/fixed.c
- src/path.c
- src/spline.c
- src/trig.c
Add missing path functionalities required for rendering TinyVG (Tiny Vector Graphics) images. Specifically, the following features have been implemented:
- Arc Ellipse
Draws an ellipse segment between the current and the target point, where `radius_x` and `radius_y` determine the both radii of the ellipse.  `large_arc` determine small(0) or larger(1) circle segment is drawn. If `sweep` is 1, the ellipse segment will make a left turn, otherwise it will make a right turn. `rotation` is the rotation of the ellipse.
- Arc circle
Draws an ellipse segment between the current and the target point, where `radius` determine the radius of the circle.  `large_arc` determine small(0) or larger(1) circle segment is drawn. If `sweep` is 1, the circle segment will make a left turn, otherwise it will …
> Support path function to fulfill TinyVG rendering

- include/twin_private.h
- src/queue.c
Removed the `free(old)` call from the `_twin_queue_delete` function, consolidating memory deallocation into the `_twin_queue_review_order` function. This change improves memory management and enhances the maintainability of the code.
The fix was verified using GDB to confirm that old is properly freed during the execution of `free(q)` in the `_twin_queue_review_order` function. Additionally, AddressSanitizer was used to confirm the absence of memory leaks and double free issues.
> Fix double free error

- apps/multi.c
- backend/vnc.c
- Register client cleanup function when during initialization to ensure that `twin_peer_t` is freed properly when the client disconnects.
- Properly release resources during VNC server shutdown by unreferencin current_fb and free the framebuffer allocated for `tx->framebuffer`
Close #76
> Fix memory leak when VNC exit

- backend/vnc.c
Previously, the VNC renderer fed the damaged region to the buffer line by line, resulting in significant rendering delays due to frequent buffer updates.
The implementation has been optimized to aggregate all updates during the current screen refresh cycle. The buffer is now updated once per refresh with the complete damaged region, reducing rendering delays and preventing screen tearing.
https://github.com/user-attachments/assets/2397db3d-a4c4-4cd6-818c-03435c5f0d89
https://github.com/user-attachments/assets/d6619129-8d06-4f99-8337-46776247206f
The table compares the performance of screen updating measuring with GIFs with significant vertical variations(Selected to better illustrate the delay caused by line-by-line buffer updates) ,  before and after optimization, measured in average …
> Optimize VNC screen update to reduce delays

- src/pixmap.c
- src/poly.c
> Correct right-bound filling

- include/twin.h
- src/screen.c
- src/window.c
Implement the twin_active_pixmap() function to find the currently active pixel map and the previously active pixel map. Utilize the window's active variable to draw different frame colors for the active window and inactive windows.
Close sysprog21#86
> Use different colors for active/inactive titles

- backend/fbdev.c
- backend/linux_vt.h
The fbdev backend supports framebuffer rendering on a specifiend VT. To enhancce its compatibility in environments with multiple TTYs, the following improvements ensure that each framebuffer device operates independently on its own VT without affecting others.
- Implement signal handlers to manage virtual terminal switching.
- Pause screen rendering when switching to another VT.
- Resume screen rendering when switching back to the original VT.
> Support VT switching for fbdev backend

- apps/spline.c
- include/twin.h
- src/box.c
- src/widget.c
Implement the twin_widget_children_paint function to repaint all the box's widgets. The issue arises when the spline updates the pixmap beneath the button widget, the pixmap of the button isn't triggered to repaint. To solve this, we call the twin_widget_paint function after the spline update to ensure the related widget will be repainted.
> Fix widgets not updating with parent's widget

- include/twin.h
- src/screen.c
- src/window.c
Implement the function twin_window_valid_range() to check whether the click coordinates fall within the window's range, based on the window's style. Originally, the logic for detecting if the window was clicked relied on the function twin_pixmap_transparent(). However, the click event won't be triggered when a transparent pixel in the window's region is clicked.
> Change the logic for window click detection

- src/draw-pixman.c
When the rendering is based on Pixman, the title bar and the gaps on the far right and bottom of the window will be rendered. However, these regions should not be accessible. Implement a check for the window's clipping variable to ensure that only the accessible pixel range is rendered.
> Fix the wrong range of pixel map for pixman

- apps/main.c
- src/screen.c
- src/window.c
Remove the inefficiently function twin_active_pixmap(). This function finds the currently and previously active window pixel map by traversing the list of pixel maps. This function will be called every time the screen needs to be updated. Set the active variable of the window only when the window's event TwinEventButtonDown is triggered to avoid redundant operations. Additionally, implement the function twin_window_active_paint() to only repaint the title bar instead of calling the function twin_window_draw() to indirectly call the function twin_window_frame to repaint the title bar of the window.
Close #92
> Fix active window not working on the framebuffer

- Makefile
Since pthread is explicitly used in `linux_input.c` (which is used in builds for fbdev), it is necessary to add pthread to the `TARGET_LIBS` list to ensure the build completes successfully.
> Fix missing -pthread for fbdev builds

- apps/multi.c
- configs/Kconfig
- include/twin.h
- include/twin_private.h
- src/draw-common.c
- src/image.c
- src/pixmap.c
- src/screen.c
- src/window.c
Use Pascal's Triangle to approximate a 5x5 Gaussian Kernel, and apply Gaussian blur on the `twin_pixmap_t` to implement the blurring technique.
See: sysprog21#34 
This PR introduces configurable drop shadow effects for active windows using an optimized stack blur algorithm. The implementation includes customizable shadow offsets, blur radius, and color settings through Kconfig. The changes focus on window rendering and pixmap handling, with performance optimizations in the blur implementation.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 3
</div>
> Render drop shadow for active window

- src/widget.c
This pull request improves code clarity by removing a duplicate comment in the widget painting function, enhancing readability and maintenance without changing functionality.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 1
</div>
> Remove duplicate comment

- src/cursor.c
The coordinates (x,y) of the cursor should not be set to the cursor's width (14) and height (20). Instead, the coordinates should be set to (0,0), ensuring that the cursor's hotspot is correctly aligned at the intended position. 
This pull request fixes a bug in the cursor positioning logic by updating the coordinates from (14,20) to (0,0). This adjustment ensures the cursor's hotspot is correctly aligned, enhancing the overall user experience.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>
> Fix the cursor position

- apps/spline.c
Change the control point hit detection from spline width to a dedicated control point radius. Introduce macros to define different lengths for easier configuration. 
This pull request enhances the control point hit detection by replacing spline width with a defined control point radius. It introduces macros for easier adjustments of control point radius, backbone width, and auxiliary line width, along with updates to initialization and hit detection logic.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>
> Use control point radius for hit detection

- include/twin.h
- src/draw-common.c
- src/icon.c
- src/screen.c
- src/window.c
This pull request introduces iconify and restore functionality for windows.
It also updates the logic for determining when a window is considered active.
The window frame now changes to blue only when the window is not iconified and is the topmost window. 
This pull request enhances the window management system by introducing minimize and maximize functionality, along with an iconify property in the window structure. It updates the drawing logic to reflect the active state of windows based on their minimized status, changing the window frame color accordingly.
</div>
> Add iconify and restore features on window frame

- include/twin.h
- src/pixmap.c
- src/screen.c
Add twin_pixmap_iconify() function to determine whether a pixmap is iconified. This function provides a way to access the corresponding window's iconify state, after verifying that the pixmap belongs to a window. 
This pull request introduces the function twin_pixmap_is_iconified, which checks if a pixmap is iconified based on its window state. It also updates the pixmap and screen files to allow drawing operations to bypass iconified pixmaps, enhancing window state handling in the graphical interface.
</div>
> Fix iconified pixmap check condition

- backend/fbdev.c
Windows would jump to unexpected positions when moving with the mouse on the Linux framebuffer backend. This patch, tested on Raspberry Pi 3B and virtual machines, ensures smoother and more reliable window dragging behavior. 
This pull request fixes a bug in the Linux framebuffer backend that caused windows to jump during mouse movement. It improves window dragging behavior on Raspberry Pi 3B by modifying screen update conditions, enhancing user experience.
</div>
> Fix Inaccurate Window Movement in Linux Framebuffer Backend

- apps/animation.c
- apps/clock.c
- apps/image.c
- apps/line.c
- apps/spline.c
- include/twin.h
- src/matrix.c
- src/widget.c
This commit adds twin_custom_widget_t API:
- twin_custom_widget_create() for widget creation with user data
- Helper functions for width, height, pixmap access, and paint queuing
- twin_matrix_transform_x/y() for coordinate transformations
- Proper dispatch mechanism calling base widget handlers first
It refactors all demo applications to use public API only:
- Remove twin_private.h dependencies from 'apps'
- Convert clock, line, spline, animation, image demos
- Replace internal _twin_* calls with public equivalents
Close #9 
This pull request introduces a new public custom widget API, enhancing widget creation and management with user-defined data. It refactors demo applications to eliminate …
> Implement public custom widget API

- .gitignore
- Makefile
- configs/Kconfig
- tools/perf.c
mado-perf is a standalone benchmarking program, modeled after x11perf, that evaluates the performance of compositing functions.
Expected output format:
2000 reps @   0.0140 msec (  71523084.1/sec): 1x1 argb32 source
2000 reps @   0.0140 msec (  71523084.1/sec): 1x1 argb32 source
2000 reps @   0.0130 msec (  77032700.4/sec): 1x1 argb32 source
...
2000 reps @   0.0140 msec (  71523084.1/sec): 1x1 argb32 source
80000 trep @   0.5578 msec (  73726930.6/sec): 1x1 argb32 source 
This pull request introduces 'mado-perf', a performance testing tool for benchmarking compositing functions, modeled after 'x11perf'. It includes updates to the Makefile and Kconfig for integration, along with various test cases …
> Add preliminary performance tester

- apps/clock.c
- apps/multi.c
- apps/spline.c
- include/twin.h
- src/twin_private.h
This standardizes structure and enum documentation by replacing header block descriptions with inline /**< */ comments. 
This pull request refines the documentation for the public API by replacing header block descriptions with inline comments, enhancing clarity and maintainability. It also improves the clock drawing logic and optimizes multi-window operations, particularly in background scaling and blurring effects.
</div>
> Refine documentation for public API

- src/image-gif.c
- src/path.c
- src/poly.c
- src/window.c
This adds missing NULL checks after memory allocation in multiple core files to prevent crashes when malloc fails. 
This pull request enhances application stability by adding NULL checks after memory allocations in core files, preventing potential crashes from dereferencing NULL pointers. These modifications ensure graceful handling of memory allocation failures.
</div>
> Fix NULL pointer dereferences after malloc

- src/image-gif.c
Incomplete cleanup on allocation failures is resolved. 
This pull request implements proper cleanup procedures in the GIF animation loader to address memory leaks. It ensures that all allocated resources are freed appropriately, enhancing the stability and reliability of the GIF loading functionality.
</div>
> Fix memory leaks in GIF animation loader

- src/box.c
- src/label.c
- src/pixmap.c
- src/widget.c
- src/window.c
This adds proper destroy event handling throughout the widget hierarchy to fix memory leaks:
- box: Propagate destroy events to all child widgets before destruction
- widget: Add TwinEventDestroy case to base widget dispatch
- label: Free dynamically allocated label text on destroy
- window: Invoke destroy callbacks to allow proper resource cleanup
- pixmap: Initialize window field to prevent undefined behavior 
This pull request addresses memory leaks by implementing proper destroy event handling in the widget and window lifecycle. Key changes include propagating destroy events to child widgets, freeing dynamically allocated resources, and initializing fields to prevent undefined behavior.
</div>
> Fix memory leaks in widget/window lifecycle

- src/timeout.c
- src/twin_private.h
- src/work.c
Platform-aware pointer validation is added to prevent invalid memory access when callbacks execute with freed widget pointers. It validates closures both at scheduling time and before execution.
Fixes crashes in _twin_toplevel_paint() during mouse event handling. 
This pull request implements critical bug fixes to prevent crashes from invalid closure pointers in work and timeout queues. It introduces platform-aware pointer validation, ensuring closures are validated at both scheduling and execution times, addressing memory access violations during mouse event handling.
</div>
> Prevent crashes from invalid closures in work/timeout queues

- Makefile
- src/closure.c
- src/screen.c
- src/timeout.c
- src/toplevel.c
- src/twin_private.h
- src/work.c
This commit implements a defensive closure tracking that validates pointers before callback execution in work queues and timeout systems. 
This pull request implements a closure lifetime tracking system in the Twin window and widget management systems to prevent use-after-free vulnerabilities. Key enhancements include closure pointer management, validation, and reference counting, improving the safety and reliability of callbacks. The Makefile has also been updated to support these changes.
</div>
> Add closure lifetime tracking to prevent use-after-free

- src/widget.c
This commit ensures custom widgets are unregistered from dispatch map before memory is freed. Previously, widget memory could be freed while still registered in the dispatch map, causing crashes when accessing freed widget pointers.
The fix modifies custom_widget_dispatch() to handle TwinEventDestroy, ensuring unregistration occurs before base widget destruction. 
This pull request fixes a critical memory management bug in custom widgets by modifying the `custom_widget_dispatch` function to correctly handle destruction events. This ensures proper unregistration of widgets from the dispatch map before memory is freed, enhancing the stability of the widget system.
</div>
> Fix use-after-free in custom widget destruction
